name: We are go
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81b9de'
    - '#508be7'
    - '#080a16'
    - '#022ca2'
    - '#0368b0'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
